### ISSUE TITLE
code/design review tops

### ISSUE THREAD

**Issue by Annevd** [OvenMagnetron/the-startup-responsive-interactieve-website#1]
Tops:

- Goed dat je een active state heb op de pagina waar je bent.
- Alles is tot nu toe goed responsive, goed dat de navigatie van ingeklapt naar volledig gaat.
- Ziet er mooi uit, je hebt goed de huisstijl aangehouden.
- Logo & animatie.
- Goede semantische HTML, clean en geen onnodige divs.
- CSS ook duidelijk gestructureerd.

**Comment by Jesse-Kramer** [comment]
Bedankt!
