### ISSUE TITLE
SVG Menu active/focus state

### ISSUE THREAD

**Issue by Annevd** [OvenMagnetron/the-startup-responsive-interactieve-website#2]
De svg naast de menu knop kleurt niet mee tijdens de active state.

![image](https://github.com/OvenMagnetron/the-startup-responsive-interactieve-website/assets/144004647/b868ae96-a18c-4ada-9b3c-388b87432d16)

**Comment by Jesse-Kramer** [comment]
Kan dit helaas niet oplossen.
