### ISSUE TITLE
Het lijkt dat je een attribute mist

### ISSUE THREAD

**Issue by lisavanmansom** [OvenMagnetron/the-startup-responsive-interactieve-website#4]
<img width="1229" alt="Scherm­afbeelding 2024-01-19 om 11 46 54" src="https://github.com/OvenMagnetron/the-startup-responsive-interactieve-website/assets/144007419/635bb492-0e4d-4504-896a-c3d3dfffd661">

Het lijkt dat je link een attribute mist, je zou  "itemprop, property, rel" kunnen toevoegen

https://github.com/OvenMagnetron/the-startup-responsive-interactieve-website/blob/4706cb5aac9e95459b30704fe4054b89c0bfce72/index.html#L33

Bron: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes

**Comment by Jesse-Kramer** [comment]
Opgelost!
https://github.com/fdnd-task/the-startup-responsive-interactieve-website/commit/5c2008e4be920943cbd7022fdd80f9755900995f
