### ISSUE TITLE
Trailing slash in niet perse nodig bij sommige elementen

### ISSUE THREAD

**Issue by DamianR2004** [OvenMagnetron/the-startup-responsive-interactieve-website#5]
De validator vind het niet leuk als er gebruik wordt gemaakt van een / aan het einde van een meta of link. Het heeft geen invloed op de pagina als je deze weg haalt. 

https://github.com/OvenMagnetron/the-startup-responsive-interactieve-website/blob/4706cb5aac9e95459b30704fe4054b89c0bfce72/index.html#L22

**Comment by Jesse-Kramer** [comment]
Opgelost!
https://github.com/fdnd-task/the-startup-responsive-interactieve-website/commit/5c2008e4be920943cbd7022fdd80f9755900995f
