### ISSUE TITLE
Element aanwezig zonder content

### ISSUE THREAD

**Issue by DamianR2004** [OvenMagnetron/the-startup-responsive-interactieve-website#6]
Er staat nu nog een element in met de naam 'q42'. Ik zou deze persoonlijk weghalen als het niet wordt gebruikt.

https://github.com/OvenMagnetron/the-startup-responsive-interactieve-website/blob/4706cb5aac9e95459b30704fe4054b89c0bfce72/index.html#L83

**Comment by Jesse-Kramer** [comment]
Dit is het logo van Q42

**Comment by KrijnHoetmer** [comment]
Tijd om ze te vertellen over [custom elements](https://developer.mozilla.org/en-US/docs/Web/API/Web_Components/Using_custom_elements) ;)
