### ISSUE TITLE
Element mist bepaalde Attributen

### ISSUE THREAD

**Issue by RobbyRisse** [OvenMagnetron/the-startup-responsive-interactieve-website#8]
Element [link] mist bepaalde attributen, namelijk: itemprop, property, rel.

Dat is hier te zien:

 ```
<link href="./images/touch-icon-precomposed.png" type="image/png" />
```

in dit geval mis je het rel attribuut oftwel relatie
hier een voorbeeld van hoe het zou kunnen: 

`<link href="./images/touch-icon-precomposed.png" rel="icon" type="image/png">
`

Ik heb informatie van MDN Html Elements gebruikt als bron, deze code hielp me daarbij: 
```
<link
  rel="apple-touch-icon"
  sizes="114x114"
  href="apple-icon-114.png"
  type="image/png" />
```

Bron: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link

**Comment by Jesse-Kramer** [comment]
Opgelost!
https://github.com/fdnd-task/the-startup-responsive-interactieve-website/commit/5c2008e4be920943cbd7022fdd80f9755900995f
