### ISSUE TITLE
Het lijkt erop dat je een onnodige slash (/) hebt

### ISSUE THREAD

**Issue by Patrickkhr** [OvenMagnetron/the-startup-responsive-interactieve-website#9]
https://github.com/OvenMagnetron/the-startup-responsive-interactieve-website/blob/4706cb5aac9e95459b30704fe4054b89c0bfce72/index.html#L5

Je sluit hier de meta tag af 

Je hoeft de meta tag niet af te sluiten het heeft geen effect.

**Comment by Jesse-Kramer** [comment]
Ik heb het gefixed
https://github.com/fdnd-task/the-startup-responsive-interactieve-website/commit/5c2008e4be920943cbd7022fdd80f9755900995f
